class Empleado{
    constructor(
        IDEmpleado,
		NombreEmpleado,
		ApePatEmpleado,
        ApeMatEmpleado,
        CorreoEmpleado,
        TelefonoEmpleado,
        Username,
        Contrasena
    ){
        this.IDEmpleado,
		this.NombreEmpleado,
		this.ApePatEmpleado,
        this.ApeMatEmpleado,
        this.CorreoEmpleado,
        this.TelefonoEmpleado,
        this.Username,
        this.Contrasena
    }
}
module.exports=Empleado;