class Reparacion{
    constructor(
        IDReparacion,
        IDVenta,
		Estatus,
        Observaciones,
		IDServicio,
        IDVehiculo,
        IDMecanico
    ){
        this.IDReparacion,
        this.IDVenta,
		this.Estatus,
        this.Observaciones,
		this.IDServicio,
        this.IDVehiculo,
        this.IDMecanico
    }
}
module.exports=Reparacion;